.only-branches: &only-branches
  except:
    - master
    - develop
    - tags
    - triggers
.not-branches: &not-branches
  only:
    - master
    - develop
    - tags
variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -DskipDwpLegacy=true"
cache:
  paths:
    - .m2/repository/
image: $CI_REGISTRY/integration/provisioning/openjdk-maven:openjdk8-maven3.5.3
stages:
  - AT-tests
  - report
  - compliance
  - code-quality
test:
  stage: AT-tests
  image: centos:7
  script:
    # Install dependancies
    - yum install maven -y
    - yum install gnupg2 -y
    - yum install sudo -y
    - yum install awscli -y
    - yum install https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm -y
    - yum install Xvfb -y
    # Install dependencies.
    - yum update -y
    - yum install unzip -y
    - yum install -y google-chrome-stable -y
    # Create axwaygsi user
    - useradd -m test-user -p password
    # Create folder to copy project
    - mkdir -p "/code"
    - chmod 777 /code
    # Set ownerships
    - chown -R test-user:root /code
    # Copy SFT AT
    - cp -R * /code
    - cd /code



    - sudo cp -f /code/src/main/java/utils/drivers/mac/chromedriverheadless /usr/local/bin/chromedriver
    - sudo chown root:root /usr/local/bin/chromedriver
    - sudo chmod 0755 /usr/local/bin/chromedriver

    - sudo mv -f /code/src/main/java/utils/drivers/mac/selenium-server-standalone.jar /usr/local/bin/
    - sudo chown root:root /usr/local/bin/selenium-server-standalone.jar
    - sudo chmod 0755 /usr/local/bin/selenium-server-standalone.jar


    - mvn clean install test -Dtest=RunnerClass






