image: maven:latest
stages:
     - build
     - test
     
build:     
     stage: build
     script:
       - echo Maven pulled
test:
     stage: test
     script:
       - mvn clean install test -Dtest=RunnerClass
