image: maven:latest
image: openjdk:latest
stages:
     - build
     - test
     
build:     
     stage: build
     script:
       - echo Maven image pulled
test:
     stage: test
     script:
       - mvn clean install test -Dtest=RunnerClass
